name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use Node.js 18.x as recommended for Vite

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the app
      - name: Build the app
        run: npm run build

      # Step 5: Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SECRET_RED }}
          action: "upload" # This tells Azure to deploy your app
          app_location: "/" # Root of your app source code
          api_location: "" # No API used
          output_location: "dist" # Where your app build files are output
